version: '2'
networks:
    mysql-phpmyadmin:
        name: mysql-phpmyadmin
        driver: bridge

volumes:
    mysqldata:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '${HOME}/server/mysql-phpmyadmin/data'

services:
    mysql:
        image: mysql:8.0
        container_name: mysql-reventa
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: reventa
            MYSQL_USER: reventa_user
            MYSQL_PASSWORD: reventa_pass
        ports:
            - "6033:3306"
        volumes:
            - mysqldata:/var/lib/mysql
            - ./init:/docker-entrypoint-initdb.d
        networks:
            mysql-phpmyadmin:
                aliases:
                - mysql

    phpmyadmin:
        image: phpmyadmin:5.2.0
        container_name: phpmyadmin-reventa
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - 8081:80
        networks:
            mysql-phpmyadmin:
                aliases:
                - phpmyadmin
